### ISSUE TITLE
Due Date Calculations are off

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1680] opened 2019-04-18 18:24 UTC
When you set a due date in a task, the date that is being generated is not correct. In this example the due date is set to one hour after the task is assigned, but you can see in the database the dates are all over the place. 

Task Config:

<img width="277" alt="Screenshot 2019-04-18 11 11 47" src="https://user-images.githubusercontent.com/535300/56381852-d36dfe80-61ca-11e9-9306-3ed80ed19396.png">

Task List with generated tasks

<img width="887" alt="Screenshot 2019-04-18 11 12 03" src="https://user-images.githubusercontent.com/535300/56381851-d36dfe80-61ca-11e9-91d5-919dca51824c.png">

Database records

<img width="731" alt="Screenshot 2019-04-18 11 23 31" src="https://user-images.githubusercontent.com/535300/56382532-7a06cf00-61cc-11e9-9453-e0438a41633d.png">

**Comment by milaendo** [comment] 2019-05-06 19:43
closing because I haven't been able to reproduce again

**Closed by milaendo** 2019-05-06 19:43 UTC
Labels: bug
